### ISSUE TITLE
Team12 Review - Design (MIS) - filterData & smoothData transitions to a state where the variable doesnt exist

### ISSUE THREAD

**Issue by AntonKanug** [paezha/PyERT-BLACK#18]
filterData & smoothData in MIS of GPS Data Preprocessing Module (Section 6) contains transitions to a state that doesn't exist. 

For both functions a Boolean value is calculated and assigned to ```data``` but this state variable doesn't exist. 

The input variable ```data``` is reassigned and this intended action of filtering the data where x!=y is not represented in this transition as a boolean value is calculated instead of a modification/filter.

<img width="484" alt="Screenshot 2023-01-20 at 4 03 16 PM" src="https://user-images.githubusercontent.com/39676112/213804767-cc3d6daf-822d-44ee-80f6-fae730b14698.png">

**Comment by LilVegedog** [comment]
Issue fixed. Thanks for your review!
