### ISSUE TITLE
Team12 Review: Design Doc - Usage of Abstract Data Types

### ISSUE THREAD

**Issue by Tamas-Leung** [paezha/PyERT-BLACK#19]
The table in section 4 is for primitive types in software engineering.
Types such as Point and Polygon are not primitives and should be defined as an abstract data type for modules to use.

![image](https://user-images.githubusercontent.com/57273388/213806727-7c23f233-c05d-48a5-b327-da6307c6e046.png)

**Comment by LilVegedog** [comment]
Issue fixed. Thanks for your review!
