### ISSUE TITLE
Team15 Review: Fit Criterion for OE1

### ISSUE THREAD

**Issue by agentvv** [paezha/PyERT-BLACK#2]
The fit criterion for the Non-Functional Requirement OE1 currently reads: "The program shall successfully run on any desktop and laptop using Windows or Linux with Python installed". 

I think there are a couple of issues with the fit criterion:
- It is not verifiable; there is no way to test all desktops and laptops using Windows or Linux with Python installed.
- It has no mention of computers with the macOS operating system, which a decently large portion of users have.

@samm82

**Comment by LilVegedog** [comment]
Issue fixed. Thanks for your review!
