### ISSUE TITLE
Team12 Review - Design (System Design Doc) - No testing mentioned in timeline

### ISSUE THREAD

**Issue by ZhimingZhao** [paezha/PyERT-BLACK#20]
On the rubric for timeline, the following requirement is written: 'Full testing/verification does not have to be part of the timeline, but **enough testing has to be included** to have confidence in Rev 0.' There's no mention of any testing in the timeline section.
![image](https://user-images.githubusercontent.com/25267171/213810442-bf163309-8fa0-4a18-88a8-392bcd1e955e.png)

**Comment by LilVegedog** [comment]
Issue fixed. Thanks for your review!
