### ISSUE TITLE
Team 32 Review: MG - Section 4 Anticipated and unlikely changes

### ISSUE THREAD

**Issue by Edwardhyw** [paezha/PyERT-BLACK#23]
In this section, you could provide some rational for each decision explaining why the implementation is likely to change or not. For example, explaining why the network analysis algorithm is likely to change, is it because of the limitation or weakness of your proposed method? This can provide reader a bettter understanding of such decision.
![Screenshot 2023-01-20 224559](https://user-images.githubusercontent.com/114092798/213842188-3e87f6f6-328a-4fa2-9f80-dbdcb195926a.png)

**Comment by LilVegedog** [comment]
Issue fixed. Thanks for your review!
