### ISSUE TITLE
Team12 Review - Design (MIS) - Software Decision modules not documented in MIS

### ISSUE THREAD

**Issue by Tamas-Leung** [paezha/PyERT-BLACK#25]
Although, the software decision modules are not implemented by PyERT, they should be documented in the MIS to explain what functions you are calling and what each function will be doing. 

List of software decision modules however they do not exist in the MIS
![image](https://user-images.githubusercontent.com/57273388/213886559-e7724110-a085-49a8-86f5-33912c3f854b.png)

**Comment by LilVegedog** [comment]
It has been mentioned by Dr. Smith in the discussion board that MIS will only document the modules that we will be implementing
