### ISSUE TITLE
Team15 Review: A few nitpicks with acronyms

### ISSUE THREAD

**Issue by jandricd** [paezha/PyERT-BLACK#3]
Few nitpicks:
- One thing I noticed was that the acronyms are not in any particular order. It's not a huge deal because there aren't that many, but it's still a little difficult to parse through them.
- I think it would be good to first write the word first, then the acronym. For example, "This project aims to re-implement the features in GIS-based Episode Reconstruction Toolkit (GERT) ...". This would be helpful for reading, as it eliminates the need to scroll up to find an acronym the first time it is seen.
- I also couldn't find a definition for RCA variables which appears in the work partitioning and in the functional requirements.

**Comment by jandricd** [comment]
@samm82

**Comment by LilVegedog** [comment]
Issue fixed. Thanks for your review!
