### ISSUE TITLE
Team 15 Review: Functional Reqs. #8 and #10 Are Not Atomic

### ISSUE THREAD

**Issue by Adham-Badawy** [paezha/PyERT-BLACK#5]
Hey guys, I think you can split your 10th FR. about error handling into two separate ones. It currently mentions properly handling run-time errors as well as displaying error messages in one requirement. Since you are "and-ing" two separate functions there, I think splitting makes for better requirements.

I think a similar thing is happening in FR #8, where it mentions generating alternative routes AND assigning values to the RCA variables. Its possible for this one I missed some domain specific knowledge that says those are actually the same thing and not two different pieces of code, but you guys can figure that one out ;). 

P.S. This wasn't enough for an issue by itself but I think the Fit Criterion for FR #6 got mixed up with a rationale or something else? Idk it just seems off you might wanna review.

Have a good reading week!

**Comment by jandricd** [comment]
@samm82

**Comment by LilVegedog** [comment]
Issue fixed. Thanks for your review!
